#!/usr/bin/env sh

set -e

methods="$(cd src && python3 -c '
from methods import strtofunc as d
for s in d.keys():
    print(s)'
)"

printf "%s\n" "$methods" | while IFS= read -r method; do
    src/main.py --method="$method" "${@:-"data/barbara.png"}" &
done

wait
